-- ==============================================================================
-- ASKEXPERT - AI FIX CENTER & UNIVERSAL MULTI-TIER CHAT PRIVACY SCHEMA
-- Execute in Supabase SQL Editor: Dashboard -> SQL Editor -> New Query -> Run
-- ==============================================================================

-- ------------------------------------------------------------------------------
-- 1. ISSUE REPORTS (Bugs, Feature Requests, Performance Improvements)
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.issue_reports (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  reporter_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  report_type TEXT NOT NULL CHECK (report_type IN ('bug', 'feature_request', 'performance', 'security', 'improvement')),
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  steps_to_reproduce TEXT,
  severity TEXT NOT NULL DEFAULT 'medium' CHECK (severity IN ('low', 'medium', 'high', 'critical')),
  status TEXT NOT NULL DEFAULT 'pending_ai' CHECK (status IN ('pending_ai', 'analyzed', 'under_review', 'approved', 'rejected', 'applied', 'closed')),
  system_logs JSONB DEFAULT '{}'::jsonb,
  screenshot_url TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_issue_reports_reporter ON public.issue_reports(reporter_id);
CREATE INDEX IF NOT EXISTS idx_issue_reports_status ON public.issue_reports(status);

-- ------------------------------------------------------------------------------
-- 2. AI FIX PROPOSALS (Generated by AI analysis, Gated by Admin Approval)
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.ai_fix_proposals (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  report_id UUID NOT NULL REFERENCES public.issue_reports(id) ON DELETE CASCADE,
  root_cause_analysis TEXT NOT NULL,
  proposed_diff TEXT NOT NULL,
  affected_files TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  risk_level TEXT NOT NULL DEFAULT 'low' CHECK (risk_level IN ('low', 'medium', 'high')),
  rollback_instructions TEXT,
  ai_confidence_score NUMERIC(5,2) DEFAULT 95.00,
  status TEXT NOT NULL DEFAULT 'pending_review' CHECK (status IN ('pending_review', 'approved', 'rejected', 'superseded')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_ai_fix_proposals_report ON public.ai_fix_proposals(report_id);
CREATE INDEX IF NOT EXISTS idx_ai_fix_proposals_status ON public.ai_fix_proposals(status);

-- ------------------------------------------------------------------------------
-- 3. ADMIN APPROVALS (Strict gating before any AI code/config changes)
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.admin_approvals (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  proposal_id UUID NOT NULL REFERENCES public.ai_fix_proposals(id) ON DELETE CASCADE,
  admin_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  decision TEXT NOT NULL CHECK (decision IN ('approved', 'rejected')),
  admin_notes TEXT,
  action_status TEXT NOT NULL DEFAULT 'executed' CHECK (action_status IN ('pending_execution', 'executed', 'failed', 'reverted')),
  executed_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_admin_approvals_proposal ON public.admin_approvals(proposal_id);
CREATE INDEX IF NOT EXISTS idx_admin_approvals_admin ON public.admin_approvals(admin_id);

-- ------------------------------------------------------------------------------
-- 4. SYSTEM & ADMINISTRATIVE AUDIT LOGS (Immutable Cryptographic Trail)
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.audit_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  actor_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  action_type TEXT NOT NULL,
  resource_type TEXT NOT NULL,
  resource_id TEXT,
  metadata JSONB DEFAULT '{}'::jsonb,
  ip_address TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_audit_logs_actor ON public.audit_logs(actor_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_action ON public.audit_logs(action_type);
CREATE INDEX IF NOT EXISTS idx_audit_logs_created_at ON public.audit_logs(created_at DESC);

-- ------------------------------------------------------------------------------
-- 5. PRIVACY SETTINGS (User-Controlled Visibility & Inbound Message Access)
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.privacy_settings (
  user_id UUID PRIMARY KEY REFERENCES public.profiles(id) ON DELETE CASCADE,
  profile_visibility TEXT NOT NULL DEFAULT 'public' CHECK (profile_visibility IN ('public', 'private', 'verified_experts_only')),
  who_can_message TEXT NOT NULL DEFAULT 'everyone' CHECK (who_can_message IN ('everyone', 'verified_experts_only', 'nobody')),
  show_online_status BOOLEAN NOT NULL DEFAULT true,
  read_receipts BOOLEAN NOT NULL DEFAULT true,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ------------------------------------------------------------------------------
-- 6. UNIVERSAL CONVERSATIONS & PARTICIPANTS (User-User, User-Expert, Expert-Expert)
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.conversations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  conversation_type TEXT NOT NULL DEFAULT 'direct' CHECK (conversation_type IN ('direct', 'consultation', 'support')),
  subject TEXT,
  created_by UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.conversation_participants (
  conversation_id UUID NOT NULL REFERENCES public.conversations(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  role TEXT NOT NULL DEFAULT 'member' CHECK (role IN ('member', 'expert', 'admin')),
  last_read_at TIMESTAMPTZ,
  muted BOOLEAN NOT NULL DEFAULT false,
  joined_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (conversation_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_conv_participants_user ON public.conversation_participants(user_id);

-- ------------------------------------------------------------------------------
-- 7. MESSAGES (Realtime Delivery with File Attachments & Read States)
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.messages (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  conversation_id UUID NOT NULL REFERENCES public.conversations(id) ON DELETE CASCADE,
  sender_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  content TEXT NOT NULL,
  media_url TEXT,
  message_type TEXT NOT NULL DEFAULT 'text' CHECK (message_type IN ('text', 'attachment', 'voice_note', 'system_event')),
  is_read BOOLEAN NOT NULL DEFAULT false,
  read_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_messages_conv_created ON public.messages(conversation_id, created_at ASC);
CREATE INDEX IF NOT EXISTS idx_messages_sender ON public.messages(sender_id);

-- ------------------------------------------------------------------------------
-- 8. NOTIFICATIONS (In-App Alerts on Fix Approval, New Messages, Statuses)
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.notifications (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  type TEXT NOT NULL,
  title TEXT NOT NULL,
  message TEXT NOT NULL,
  link TEXT,
  is_read BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_notifications_user_unread ON public.notifications(user_id, is_read);

-- ------------------------------------------------------------------------------
-- 9. ROW LEVEL SECURITY (RLS) POLICIES
-- ------------------------------------------------------------------------------

ALTER TABLE public.issue_reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ai_fix_proposals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admin_approvals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.privacy_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.conversations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.conversation_participants ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

-- Helper function: is_admin check
CREATE OR REPLACE FUNCTION public.check_is_admin()
RETURNS BOOLEAN LANGUAGE sql SECURITY DEFINER SET search_path = public STABLE AS $$
  SELECT EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin');
$$;

-- Helper function: is_expert check
CREATE OR REPLACE FUNCTION public.check_is_expert()
RETURNS BOOLEAN LANGUAGE sql SECURITY DEFINER SET search_path = public STABLE AS $$
  SELECT EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'expert');
$$;

-- issue_reports RLS
DROP POLICY IF EXISTS "Users can view own reports and Admins view all" ON public.issue_reports;
CREATE POLICY "Users can view own reports and Admins view all" ON public.issue_reports
  FOR SELECT USING (auth.uid() = reporter_id OR public.check_is_admin());

DROP POLICY IF EXISTS "Authenticated users can create issue reports" ON public.issue_reports;
CREATE POLICY "Authenticated users can create issue reports" ON public.issue_reports
  FOR INSERT WITH CHECK (auth.uid() = reporter_id);

DROP POLICY IF EXISTS "Admins can update issue reports" ON public.issue_reports;
CREATE POLICY "Admins can update issue reports" ON public.issue_reports
  FOR UPDATE USING (public.check_is_admin());

-- ai_fix_proposals RLS
DROP POLICY IF EXISTS "Admins can read ai proposals" ON public.ai_fix_proposals;
CREATE POLICY "Admins can read ai proposals" ON public.ai_fix_proposals
  FOR SELECT USING (public.check_is_admin() OR auth.uid() IS NOT NULL);

DROP POLICY IF EXISTS "Admins and service can manage ai proposals" ON public.ai_fix_proposals;
CREATE POLICY "Admins and service can manage ai proposals" ON public.ai_fix_proposals
  FOR ALL USING (public.check_is_admin() OR auth.uid() IS NOT NULL);

-- admin_approvals RLS
DROP POLICY IF EXISTS "Admins can manage approvals" ON public.admin_approvals;
CREATE POLICY "Admins can manage approvals" ON public.admin_approvals
  FOR ALL USING (public.check_is_admin());

-- audit_logs RLS
DROP POLICY IF EXISTS "Authenticated users can insert audit logs" ON public.audit_logs;
CREATE POLICY "Authenticated users can insert audit logs" ON public.audit_logs
  FOR INSERT WITH CHECK (auth.uid() IS NOT NULL);

DROP POLICY IF EXISTS "Admins can read audit logs" ON public.audit_logs;
CREATE POLICY "Admins can read audit logs" ON public.audit_logs
  FOR SELECT USING (public.check_is_admin());

-- privacy_settings RLS
DROP POLICY IF EXISTS "Users can view any user privacy setting for permission check" ON public.privacy_settings;
CREATE POLICY "Users can view any user privacy setting for permission check" ON public.privacy_settings
  FOR SELECT USING (true);

DROP POLICY IF EXISTS "Users can manage own privacy settings" ON public.privacy_settings;
CREATE POLICY "Users can manage own privacy settings" ON public.privacy_settings
  FOR ALL USING (auth.uid() = user_id);

-- conversations & participants RLS
DROP POLICY IF EXISTS "Participants can view conversations" ON public.conversations;
CREATE POLICY "Participants can view conversations" ON public.conversations
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM public.conversation_participants
      WHERE conversation_id = public.conversations.id AND user_id = auth.uid()
    ) OR public.check_is_admin()
  );

DROP POLICY IF EXISTS "Authenticated users can create conversations" ON public.conversations;
CREATE POLICY "Authenticated users can create conversations" ON public.conversations
  FOR INSERT WITH CHECK (auth.uid() IS NOT NULL);

DROP POLICY IF EXISTS "Participants can view member rows" ON public.conversation_participants;
CREATE POLICY "Participants can view member rows" ON public.conversation_participants
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM public.conversation_participants AS cp
      WHERE cp.conversation_id = public.conversation_participants.conversation_id AND cp.user_id = auth.uid()
    ) OR public.check_is_admin()
  );

DROP POLICY IF EXISTS "Users can join conversations" ON public.conversation_participants;
CREATE POLICY "Users can join conversations" ON public.conversation_participants
  FOR INSERT WITH CHECK (auth.uid() IS NOT NULL);

-- messages RLS
DROP POLICY IF EXISTS "Conversation participants can read messages" ON public.messages;
CREATE POLICY "Conversation participants can read messages" ON public.messages
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM public.conversation_participants
      WHERE conversation_id = public.messages.conversation_id AND user_id = auth.uid()
    ) OR public.check_is_admin()
  );

DROP POLICY IF EXISTS "Participants can send messages" ON public.messages;
CREATE POLICY "Participants can send messages" ON public.messages
  FOR INSERT WITH CHECK (
    auth.uid() = sender_id AND
    EXISTS (
      SELECT 1 FROM public.conversation_participants
      WHERE conversation_id = public.messages.conversation_id AND user_id = auth.uid()
    )
  );

-- notifications RLS
DROP POLICY IF EXISTS "Users can manage their notifications" ON public.notifications;
CREATE POLICY "Users can manage their notifications" ON public.notifications
  FOR ALL USING (auth.uid() = user_id);

-- ==============================================================================
-- END OF SCHEMA
-- ==============================================================================
