import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://girexuzrkeiylkbqglks.supabase.co";
const SUPABASE_ANON_KEY = "sb_publishable_KryT6X0fLpvKJdSbUx3HpA_nkZYr98P";

const supabase = createClient(SUPABASE_URL, SUPABASE_ANON_KEY);

const experts = [
  // 1. Legal Advisor / Lawyer
  {
    id: "11111111-1111-1111-1111-111111111111",
    full_name: "Adv. Vikram Rao",
    role: "expert",
    username: "vikram_rao",
    email: "vikram.rao@askexpert.com",
    phone: "+91 98765 11111",
    headline: "Senior Corporate & Regulatory Attorney",
    specialization: "Legal Advisor / Lawyer",
    experience_years: 12,
    languages: ["English", "Hindi", "Marathi"],
    rating: 4.90,
    reviews_count: 184,
    consultation_fee: 1200.00,
    avatar_url: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80",
    skills: ["Corporate Law", "Contract Negotiation", "Arbitration", "MCA Filings"],
    availability_status: "available",
    account_status: "active",
    bio: "Over 12 years of experience handling corporate litigation, merger agreements, compliance and arbitration."
  },
  {
    id: "11111111-1111-1111-1111-222222222222",
    full_name: "Adv. Sunita Reddy",
    role: "expert",
    username: "sunita_reddy",
    email: "sunita.reddy@askexpert.com",
    phone: "+91 98765 11112",
    headline: "High Court Criminal & Constitutional Law Specialist",
    specialization: "Legal Advisor / Lawyer",
    experience_years: 15,
    languages: ["English", "Telugu", "Hindi"],
    rating: 4.95,
    reviews_count: 240,
    consultation_fee: 1800.00,
    avatar_url: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?auto=format&fit=crop&w=300&q=80",
    skills: ["Criminal Defense", "Family Law", "Property Disputes", "Bail Applications"],
    availability_status: "available",
    account_status: "active",
    bio: "Senior advocate specializing in criminal defense, marital disputes, and property litigation."
  },
  {
    id: "11111111-1111-1111-1111-333333333333",
    full_name: "Adv. Devendra Sharma",
    role: "expert",
    username: "devendra_sharma",
    email: "devendra.sharma@askexpert.com",
    phone: "+91 98765 11113",
    headline: "Cyber Law, Data Privacy & IP Rights Advocate",
    specialization: "Legal Advisor / Lawyer",
    experience_years: 8,
    languages: ["English", "Hindi"],
    rating: 4.80,
    reviews_count: 112,
    consultation_fee: 1000.00,
    avatar_url: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80",
    skills: ["Cyber Law", "GDPR/DPDP Compliance", "IT Act", "Copyrights & Trademarks"],
    availability_status: "available",
    account_status: "active",
    bio: "Cyber security legal consultant advising tech startups and digital enterprises."
  },

  // 2. Chartered Accountant / Tax Expert
  {
    id: "22222222-2222-2222-2222-222222222222",
    full_name: "CA Ananya Sharma",
    role: "expert",
    username: "ananya_sharma",
    email: "ananya.sharma@askexpert.com",
    phone: "+91 98765 22221",
    headline: "Chartered Accountant & Corporate Tax Consultant",
    specialization: "Chartered Accountant / Tax Expert",
    experience_years: 9,
    languages: ["English", "Hindi", "Gujarati"],
    rating: 5.00,
    reviews_count: 210,
    consultation_fee: 1500.00,
    avatar_url: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=300&q=80",
    skills: ["GST Audit", "Corporate Tax", "Transfer Pricing", "TDS Returns"],
    availability_status: "available",
    account_status: "active",
    bio: "Chartered Accountant with expert knowledge in GST compliance and corporate tax planning."
  },
  {
    id: "22222222-2222-2222-2222-333333333333",
    full_name: "CA Rajesh Agarwal",
    role: "expert",
    username: "rajesh_agarwal",
    email: "rajesh.agarwal@askexpert.com",
    phone: "+91 98765 22222",
    headline: "Income Tax Appeals & NRI Taxation Specialist",
    specialization: "Chartered Accountant / Tax Expert",
    experience_years: 14,
    languages: ["English", "Hindi", "Bengali"],
    rating: 4.90,
    reviews_count: 165,
    consultation_fee: 2200.00,
    avatar_url: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=300&q=80",
    skills: ["NRI Tax", "Scrutiny Assessment", "Capital Gains", "Tax Structuring"],
    availability_status: "available",
    account_status: "active",
    bio: "Senior CA handling high-net-worth tax litigation, income tax tribunals, and cross-border assets."
  },
  {
    id: "22222222-2222-2222-2222-444444444444",
    full_name: "CA Preeti Kulkarni",
    role: "expert",
    username: "preeti_kulkarni",
    email: "preeti.kulkarni@askexpert.com",
    phone: "+91 98765 22223",
    headline: "Startup Financial Audit & Bookkeeping Advisor",
    specialization: "Chartered Accountant / Tax Expert",
    experience_years: 7,
    languages: ["English", "Marathi", "Hindi"],
    rating: 4.85,
    reviews_count: 98,
    consultation_fee: 950.00,
    avatar_url: "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=300&q=80",
    skills: ["Startup Compliance", "MCA Audit", "Financial Modeling", "Payroll Management"],
    availability_status: "available",
    account_status: "active",
    bio: "Helping early-stage startups build clean books, tax compliance, and investor-ready reporting."
  },

  // 3. Software & Cloud Architect
  {
    id: "33333333-3333-3333-3333-333333333333",
    full_name: "Dr. Rahul Kumar",
    role: "expert",
    username: "rahul_kumar",
    email: "rahul.kumar@askexpert.com",
    phone: "+91 98765 33331",
    headline: "Software Architect & Tech Patent Specialist",
    specialization: "Software & Cloud Architect",
    experience_years: 15,
    languages: ["English", "Hindi", "Kannada"],
    rating: 4.80,
    reviews_count: 95,
    consultation_fee: 2000.00,
    avatar_url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80",
    skills: ["Cloud Architecture", "Enterprise Systems", "Patent Prosecution", "Tech Licensing"],
    availability_status: "available",
    account_status: "active",
    bio: "Software architect and IP consultant guiding enterprises through cloud modernization."
  },
  {
    id: "33333333-3333-3333-3333-444444444444",
    full_name: "Karthik Viswanathan",
    role: "expert",
    username: "karthik_v",
    email: "karthik.v@askexpert.com",
    phone: "+91 98765 33332",
    headline: "Principal AWS & Kubernetes Infrastructure Architect",
    specialization: "Software & Cloud Architect",
    experience_years: 11,
    languages: ["English", "Tamil", "Telugu"],
    rating: 4.95,
    reviews_count: 178,
    consultation_fee: 1800.00,
    avatar_url: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=300&q=80",
    skills: ["AWS Cloud", "Kubernetes", "DevOps Pipelines", "System Scalability", "Microservices"],
    availability_status: "available",
    account_status: "active",
    bio: "Ex-Amazon Cloud Architect helping companies scale infrastructure to millions of users."
  },
  {
    id: "33333333-3333-3333-3333-555555555555",
    full_name: "Neha Gupta",
    role: "expert",
    username: "neha_gupta",
    email: "neha.gupta@askexpert.com",
    phone: "+91 98765 33333",
    headline: "Full Stack & AI Applications Lead Consultant",
    specialization: "Software & Cloud Architect",
    experience_years: 8,
    languages: ["English", "Hindi"],
    rating: 4.88,
    reviews_count: 134,
    consultation_fee: 1400.00,
    avatar_url: "https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?auto=format&fit=crop&w=300&q=80",
    skills: ["React & Node.js", "Python AI/ML", "PostgreSQL Optimization", "System Code Reviews"],
    availability_status: "available",
    account_status: "active",
    bio: "Full-stack architect specializing in Generative AI integration, modern web applications, and web performance."
  },

  // 4. Doctor / Healthcare Specialist
  {
    id: "44444444-4444-4444-4444-444444444444",
    full_name: "Dr. Priya Patel",
    role: "expert",
    username: "priya_patel",
    email: "priya.patel@askexpert.com",
    phone: "+91 98765 44441",
    headline: "Medical Regulatory & Telehealth Advisor",
    specialization: "Doctor / Healthcare Specialist",
    experience_years: 10,
    languages: ["English", "Hindi", "Gujarati"],
    rating: 4.90,
    reviews_count: 142,
    consultation_fee: 1000.00,
    avatar_url: "https://images.unsplash.com/photo-1594824813590-78965a7dcfd6?auto=format&fit=crop&w=300&q=80",
    skills: ["Clinical Protocols", "Telehealth Law", "Ayush & Pharma", "Diagnostics"],
    availability_status: "available",
    account_status: "active",
    bio: "Physician and medical health advisor guiding digital health platforms and clinical compliance."
  },
  {
    id: "44444444-4444-4444-4444-555555555555",
    full_name: "Dr. Siddharth Verma",
    role: "expert",
    username: "siddharth_verma",
    email: "siddharth.verma@askexpert.com",
    phone: "+91 98765 44442",
    headline: "Senior Physician & Health-Tech Operations Strategist",
    specialization: "Doctor / Healthcare Specialist",
    experience_years: 16,
    languages: ["English", "Hindi", "Punjabi"],
    rating: 4.92,
    reviews_count: 205,
    consultation_fee: 1600.00,
    avatar_url: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&w=300&q=80",
    skills: ["Medical Consultation", "Preventive Health", "Clinical Trials", "Hospital Compliance"],
    availability_status: "available",
    account_status: "active",
    bio: "Experienced MD consulting on healthcare management, clinical trials, and preventive medicine."
  },
  {
    id: "44444444-4444-4444-4444-666666666666",
    full_name: "Dr. Meenakshi Sundaram",
    role: "expert",
    username: "meenakshi_s",
    email: "meenakshi.s@askexpert.com",
    phone: "+91 98765 44443",
    headline: "Public Health Advisor & Nutrition Specialist",
    specialization: "Doctor / Healthcare Specialist",
    experience_years: 12,
    languages: ["English", "Tamil", "Hindi"],
    rating: 4.87,
    reviews_count: 156,
    consultation_fee: 1100.00,
    avatar_url: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=300&q=80",
    skills: ["Clinical Nutrition", "Wellness Programs", "Disease Prevention", "Public Health Policy"],
    availability_status: "available",
    account_status: "active",
    bio: "Public health strategist providing personalized nutrition plans and corporate wellness advising."
  },

  // 5. Financial Planner & Wealth Advisor
  {
    id: "55555555-5555-5555-5555-555555555555",
    full_name: "Rajesh Menon",
    role: "expert",
    username: "rajesh_menon",
    email: "rajesh.menon@askexpert.com",
    phone: "+91 98765 55551",
    headline: "SEBI Registered Investment Advisor & Wealth Strategist",
    specialization: "Financial Planner & Wealth Advisor",
    experience_years: 14,
    languages: ["English", "Hindi", "Malayalam", "Tamil"],
    rating: 4.70,
    reviews_count: 118,
    consultation_fee: 1800.00,
    avatar_url: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80",
    skills: ["Portfolio Structuring", "Mutual Funds", "Equities", "Risk Hedging"],
    availability_status: "offline",
    account_status: "active",
    bio: "Certified wealth consultant helping families and professionals build multi-asset portfolios."
  },
  {
    id: "55555555-5555-5555-5555-666666666666",
    full_name: "Pooja Singhania",
    role: "expert",
    username: "pooja_singhania",
    email: "pooja.singhania@askexpert.com",
    phone: "+91 98765 55552",
    headline: "CFP & High Net-Worth Wealth Management Specialist",
    specialization: "Financial Planner & Wealth Advisor",
    experience_years: 10,
    languages: ["English", "Hindi", "Marwari"],
    rating: 4.90,
    reviews_count: 140,
    consultation_fee: 2100.00,
    avatar_url: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=300&q=80",
    skills: ["Retirement Planning", "Estate Planning", "Tax-Saving Investments", "Mutual Funds"],
    availability_status: "available",
    account_status: "active",
    bio: "Certified Financial Planner advising HNI clients on tax-efficient wealth management."
  },
  {
    id: "55555555-5555-5555-5555-777777777777",
    full_name: "Amitava Bannerjee",
    role: "expert",
    username: "amitava_b",
    email: "amitava.b@askexpert.com",
    phone: "+91 98765 55553",
    headline: "Personal Finance & Debt Restructuring Consultant",
    specialization: "Financial Planner & Wealth Advisor",
    experience_years: 9,
    languages: ["English", "Bengali", "Hindi"],
    rating: 4.82,
    reviews_count: 92,
    consultation_fee: 1200.00,
    avatar_url: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=300&q=80",
    skills: ["Debt Management", "Emergency Funds", "Insurance Planning", "SIP Portfolios"],
    availability_status: "available",
    account_status: "active",
    bio: "Helping salaried professionals optimize budget savings, clear high-interest debt, and invest wisely."
  },

  // 6. Business & Startup Consultant
  {
    id: "66666666-6666-6666-6666-666666666666",
    full_name: "Meera Deshmukh",
    role: "expert",
    username: "meera_deshmukh",
    email: "meera.deshmukh@askexpert.com",
    phone: "+91 98765 66661",
    headline: "Startup Expansion & Business Strategist",
    specialization: "Business & Startup Consultant",
    experience_years: 11,
    languages: ["English", "Hindi", "Marathi"],
    rating: 4.80,
    reviews_count: 88,
    consultation_fee: 1600.00,
    avatar_url: "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=300&q=80",
    skills: ["Go-to-Market", "Venture Structuring", "Pitch Decks", "Operations"],
    availability_status: "available",
    account_status: "active",
    bio: "Business strategist mentoring founders on pitch deck presentation, GTM planning, and operational scaling."
  },
  {
    id: "66666666-6666-6666-6666-777777777777",
    full_name: "Rohan Malhotra",
    role: "expert",
    username: "rohan_malhotra",
    email: "rohan.malhotra@askexpert.com",
    phone: "+91 98765 66662",
    headline: "Venture Capital Fundraising & Business Model Specialist",
    specialization: "Business & Startup Consultant",
    experience_years: 13,
    languages: ["English", "Hindi"],
    rating: 4.93,
    reviews_count: 160,
    consultation_fee: 2500.00,
    avatar_url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80",
    skills: ["Pitch Decks", "Investor Readiness", "Unit Economics", "Valuation Modeling"],
    availability_status: "available",
    account_status: "active",
    bio: "Ex-VC partner assisting startups in raising seed to Series-A capital."
  },
  {
    id: "66666666-6666-6666-6666-888888888888",
    full_name: "Shalini Nambiar",
    role: "expert",
    username: "shalini_nambiar",
    email: "shalini.nambiar@askexpert.com",
    phone: "+91 98765 66663",
    headline: "D2C E-Commerce & Retail Operations Consultant",
    specialization: "Business & Startup Consultant",
    experience_years: 8,
    languages: ["English", "Malayalam", "Hindi"],
    rating: 4.86,
    reviews_count: 104,
    consultation_fee: 1300.00,
    avatar_url: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80",
    skills: ["E-Commerce Growth", "Supply Chain", "Brand Strategy", "Digital Marketing"],
    availability_status: "available",
    account_status: "active",
    bio: "Growth consultant specializing in online DTC brands, customer acquisition, and logistics operations."
  },

  // 7. Civil Engineer / Architect
  {
    id: "77777777-7777-7777-7777-111111111111",
    full_name: "Engr. Suresh Hegde",
    role: "expert",
    username: "suresh_hegde",
    email: "suresh.hegde@askexpert.com",
    phone: "+91 98765 77771",
    headline: "Chief Structural Engineer & Infrastructure Consultant",
    specialization: "Civil Engineer / Architect",
    experience_years: 18,
    languages: ["English", "Kannada", "Hindi"],
    rating: 4.91,
    reviews_count: 215,
    consultation_fee: 2000.00,
    avatar_url: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80",
    skills: ["Structural Audit", "Building Codes", "RCC Design", "Construction Management"],
    availability_status: "available",
    account_status: "active",
    bio: "Chartered structural engineer providing safety audits, structural designs, and site inspections."
  },
  {
    id: "77777777-7777-7777-7777-222222222222",
    full_name: "Ar. Ritu Bhattacharya",
    role: "expert",
    username: "ritu_b",
    email: "ritu.b@askexpert.com",
    phone: "+91 98765 77772",
    headline: "Sustainable Architecture & Interior Design Consultant",
    specialization: "Civil Engineer / Architect",
    experience_years: 10,
    languages: ["English", "Bengali", "Hindi"],
    rating: 4.88,
    reviews_count: 125,
    consultation_fee: 1500.00,
    avatar_url: "https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?auto=format&fit=crop&w=300&q=80",
    skills: ["Sustainable Design", "3D Architectural Blueprints", "Space Planning", "LEED Certification"],
    availability_status: "available",
    account_status: "active",
    bio: "Principal Architect consulting on eco-friendly residential designs and commercial interiors."
  },

  // 8. Career & HR Counselor
  {
    id: "88888888-8888-8888-8888-111111111111",
    full_name: "Vikramaditya Joshi",
    role: "expert",
    username: "vikram_joshi",
    email: "vikram.joshi@askexpert.com",
    phone: "+91 98765 88881",
    headline: "Executive Leadership Coach & HR Transformation Consultant",
    specialization: "Career & HR Counselor",
    experience_years: 15,
    languages: ["English", "Hindi", "Gujarati"],
    rating: 4.94,
    reviews_count: 190,
    consultation_fee: 1750.00,
    avatar_url: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=300&q=80",
    skills: ["Executive Coaching", "Performance Management", "HR Policy", "Leadership Strategy"],
    availability_status: "available",
    account_status: "active",
    bio: "HR Leader guiding mid-to-executive level professionals on career growth and leadership transition."
  },
  {
    id: "88888888-8888-8888-8888-222222222222",
    full_name: "Deepa Swaminathan",
    role: "expert",
    username: "deepa_s",
    email: "deepa.s@askexpert.com",
    phone: "+91 98765 88882",
    headline: "Career Transition & Interview Success Coach",
    specialization: "Career & HR Counselor",
    experience_years: 7,
    languages: ["English", "Tamil", "Hindi"],
    rating: 4.89,
    reviews_count: 145,
    consultation_fee: 900.00,
    avatar_url: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?auto=format&fit=crop&w=300&q=80",
    skills: ["Resume Optimization", "Mock Interviews", "LinkedIn Branding", "Salary Negotiation"],
    availability_status: "available",
    account_status: "active",
    bio: "Career coach helping candidates clear tech and corporate interviews with confidence."
  },

  // 9. Education & Study Abroad Mentor
  {
    id: "99999999-9999-9999-9999-111111111111",
    full_name: "Prof. Arvind Saxena",
    role: "expert",
    username: "arvind_saxena",
    email: "arvind.saxena@askexpert.com",
    phone: "+91 98765 99991",
    headline: "Ivy League & US/UK University Admissions Mentor",
    specialization: "Education & Study Abroad Mentor",
    experience_years: 16,
    languages: ["English", "Hindi"],
    rating: 4.96,
    reviews_count: 230,
    consultation_fee: 2400.00,
    avatar_url: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=300&q=80",
    skills: ["SOP Editing", "LOR Strategy", "US/UK Applications", "Scholarship Guidance"],
    availability_status: "available",
    account_status: "active",
    bio: "Former admissions evaluator guiding students into Top 20 global universities."
  },
  {
    id: "99999999-9999-9999-9999-222222222222",
    full_name: "Sneha Roy",
    role: "expert",
    username: "sneha_roy",
    email: "sneha.roy@askexpert.com",
    phone: "+91 98765 99992",
    headline: "European University Admissions & Visa Consultant",
    specialization: "Education & Study Abroad Mentor",
    experience_years: 8,
    languages: ["English", "German", "Hindi"],
    rating: 4.85,
    reviews_count: 110,
    consultation_fee: 1250.00,
    avatar_url: "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=300&q=80",
    skills: ["Germany/Nordic Admissions", "Student Visa Process", "IELTS Prep", "Course Selection"],
    availability_status: "available",
    account_status: "active",
    bio: "Study abroad advisor specialized in tuition-free and low-cost European higher education."
  }
];

async function seedExperts() {
  console.log(`Attempting to seed ${experts.length} expert profiles into Supabase...`);
  const { data, error } = await supabase.from('profiles').upsert(experts, { onConflict: 'id' });
  if (error) {
    console.error("Error seeding experts:", error);
  } else {
    console.log(`Successfully seeded ${experts.length} experts!`);
  }
}

seedExperts();
