const fs = require('fs');
const path = require('path');

const sql = [
  '-- ==============================================================================',
  '-- ASKEXPERT - VERIFIED SCHEMA FIX + SAFE TRIGGER',
  '-- Run this in: Supabase Dashboard -> SQL Editor -> New Query -> Run',
  '-- Project: girexuzrkeiylkbqglks',
  '-- Verified against live remote schema on 2026-08-23',
  '-- Remote columns confirmed MISSING: username, phone',
  '-- ==============================================================================',
  '',
  '-- STEP 1: Add missing columns (safe - IF NOT EXISTS)',
  'ALTER TABLE public.profiles',
  '  ADD COLUMN IF NOT EXISTS username TEXT UNIQUE,',
  '  ADD COLUMN IF NOT EXISTS phone    TEXT;',
  '',
  '-- STEP 2: Replace handle_new_user() with safe version',
  'CREATE OR REPLACE FUNCTION public.handle_new_user()',
  'RETURNS TRIGGER',
  'LANGUAGE plpgsql',
  'SECURITY DEFINER',
  'SET search_path = public',
  'AS $$',
  'DECLARE',
  '  base_username TEXT;',
  '  final_username TEXT;',
  '  counter        INT := 1;',
  'BEGIN',
  "  base_username := COALESCE(",
  "    NULLIF(TRIM(NEW.raw_user_meta_data->>'username'), ''),",
  "    split_part(NEW.email, '@', 1)",
  '  );',
  "  base_username := LOWER(REGEXP_REPLACE(TRIM(base_username), '[^a-zA-Z0-9_]', '_', 'g'));",
  '  IF base_username IS NULL OR LENGTH(base_username) < 2 THEN',
  "    base_username := 'user_' || SUBSTRING(NEW.id::text FROM 1 FOR 8);",
  '  END IF;',
  '  final_username := base_username;',
  '  WHILE EXISTS (SELECT 1 FROM public.profiles WHERE username = final_username AND id <> NEW.id) LOOP',
  "    final_username := base_username || '_' || counter;",
  '    counter := counter + 1;',
  '  END LOOP;',
  '  INSERT INTO public.profiles (id, full_name, role, username, email, phone, avatar_url, headline, specialization)',
  '  VALUES (',
  '    NEW.id,',
  "    COALESCE(NULLIF(TRIM(NEW.raw_user_meta_data->>'full_name'), ''), split_part(NEW.email, '@', 1)),",
  "    COALESCE(NULLIF(TRIM(NEW.raw_user_meta_data->>'role'),      ''), 'user'),",
  '    final_username,',
  '    NEW.email,',
  "    NULLIF(TRIM(COALESCE(NEW.raw_user_meta_data->>'phone', '')), ''),",
  "    NULLIF(TRIM(COALESCE(NEW.raw_user_meta_data->>'avatar_url', '')), ''),",
  "    NULLIF(TRIM(COALESCE(NEW.raw_user_meta_data->>'headline', '')), ''),",
  "    NULLIF(TRIM(COALESCE(NEW.raw_user_meta_data->>'specialization', '')), '')",
  '  )',
  '  ON CONFLICT (id) DO UPDATE SET',
  '    full_name  = EXCLUDED.full_name,',
  '    role       = EXCLUDED.role,',
  '    username   = EXCLUDED.username,',
  '    email      = EXCLUDED.email,',
  '    phone      = EXCLUDED.phone,',
  '    updated_at = now();',
  '  RETURN NEW;',
  'EXCEPTION WHEN OTHERS THEN',
  "  RAISE WARNING 'handle_new_user() error for user %: %', NEW.id, SQLERRM;",
  '  RETURN NEW;',
  'END;',
  '$$;',
  '',
  '-- STEP 3: Reattach trigger',
  'DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;',
  'CREATE TRIGGER on_auth_user_created',
  '  AFTER INSERT ON auth.users',
  '  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();',
  '',
  '-- STEP 4: Verify result (should show existing 3 profiles)',
  'SELECT id, full_name, email, role, username, phone FROM public.profiles ORDER BY created_at DESC LIMIT 5;',
].join('\n');

const outPath = path.join(__dirname, '..', 'fix_trigger.sql');
fs.writeFileSync(outPath, sql, 'utf8');
console.log('Written:', outPath);
console.log('Size:', fs.statSync(outPath).size, 'bytes');
console.log('\nFirst 400 chars:');
console.log(sql.substring(0, 400));
console.log('\nFunction body preview (STEP 2):');
const step2Start = sql.indexOf('AS $$');
console.log(sql.substring(step2Start, step2Start + 600));
